#name: github pages

#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#       Checkout the code
#      - uses: actions/checkout@v2

#       Install .NET Core SDK
#      - name: Setup .NET Core
#        uses: actions/setup-dotnet@v2
#        with:
#          dotnet-version: 6.0.x
          
#       Install dotnet wasm buildtools workload
#      - name: Install .NET WASM Build Tools
#        run: dotnet workload install wasm-tools
          
#       Publishes Blazor project to the release-folder
#      - name: Publish .NET Core Project
#        run: dotnet publish BlazorBeerCss/BlazorBeerCssClient.csproj -c:Release -p:GHPages=true -o dist/Web --nologo

#      - name: Commit wwwroot to GitHub Pages
#        uses: JamesIves/github-pages-deploy-action@3.7.1
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          BRANCH: gh-pages
#          FOLDER: dist/Web/wwwroot
name: Deploy Blazor WASM to GitHub Pages

on:
    push:
        branches: [main]

jobs:
    deploy-to-github-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 6.x
                  include-prerelease: true

            - name: Publish .NET Core Project
              run: dotnet publish BootstrapMobile.Wasm/BootstrapMobile.Wasm.csproj -c Release -o release --nologo

            - name: copy index.html to 404.html
              run: cp release/wwwroot/index.html release/wwwroot/404.html

            - name: Add .nojekyll file
              run: touch release/wwwroot/.nojekyll

            # changes the base-tag in index.html from '/' to 'BlazorBeerCss' to match GitHub Pages repository subdirectory
            - name: Change base-tag in index.html from / to BlazorBeerCss
              run: sed -i 's/<base href="\/" \/>/<base href="\/MobileBootstrap\/" \/>/g' release/wwwroot/index.html

            - name: Commit wwwroot to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: release/wwwroot
